### ISSUE TITLE
Error while init-db

### ISSUE THREAD

**Issue by treemillsub** [Skarlso/aws_minecraft#4]
when I run the command "bundle exec ./bin/aws_minecraft.rb init-db"
 I get this error:
bundle exec ./bin/aws_minecraft.rb init-db
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems.rb:932: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-1.13.1/lib/bundler/rubygems_integration.rb:486: warning: in `eval'
bundler: command not found: ./bin/aws_minecraft.rb
Install missing gem executables with `bundle install`

**Comment by Skarlso** [comment]
Hi,
Thanks for creating an issue. I'll look into it first thing in the morning. :-)

**Comment by Skarlso** [comment]
Although this is a rather old project so might I suggest you take a look at the newer, more refined version, https://github.com/Skarlso/miner here. This also has backup capabilities. Never the less I'll take a look at the error but this project is a bit incomplete if I remeber correctly. 🤔☺️

**Comment by Skarlso** [comment]
Oh I see, this one runs the server on AWS. I totally forgot. :)

**Comment by Skarlso** [comment]
@treemillsub  done.
Turns out the gemfile was just very old. Should be okay now, please try again.

**Comment by treemillsub** [comment]
@Skarlso thanks for taking a look at this I updated the gemfile and run the command "bundle install"
and got the error:
 There was an error parsing `Gemfile`: syntax error, unexpected ':', expecting end-of-input - remote: https://rubygems.org/

**Comment by Skarlso** [comment]
@treemillsub I've got an email about a syntax error, but can't see the comment. Is it working now?

**Comment by treemillsub** [comment]
@Skarlso yeah thanks alot it works. I'm still struggling with the public key tho. whenever I encode it to Base64 format and past in the minecraft.key file and run aws_minecraft.rb create-instance  . I get this error:  Value for parameter PublicKeyMaterial is invalid. Length exceeds maximum of 2048. (Aws::EC2::Errors::InvalidParameterValue)

**Comment by Skarlso** [comment]
Yes. The EC2 instances only allow 2048 length keys. Try creating one with that length? 
Or maybe that's a restriction which no longer applies, but in turn is still enforced by aws sdk v2. But I'm reluctant to update a 4 years old project as I'm pretty sure they changed a SHITTON of things in v3. :DDD

So sorry, hope this helps somewhat. Good luck!

**Comment by Skarlso** [comment]
@treemillsub hi, were you able to solve the keylength thing?

Maybe I need to update the aws sdk after all?

**Comment by treemillsub** [comment]
@Skarlso not really. when I encrypt the key it either tells me that the max length allowed is 2048 or it said invalid encryption.

**Comment by Skarlso** [comment]
How are you encrypting it and how long is the key? Did you try it with
2048? Or is that no longer the key length aws provides?

If that's the case I do have to update the sdk I think.

**Comment by treemillsub** [comment]
ok so I'm taking the key :
 -----BEGIN RSA PRIVATE KEY-----
TUlJRXBBS....
-----END RSA PRIVATE KEY-----

and encrypting it using Base64 encode UTF-8. when I enter the encrypted key in the minecraft.key file  and run the command the error  Length exceeds maximum of 2048 is logged.

**Comment by Skarlso** [comment]
Huh. I'll spin this up again and see what's going on.

**Comment by Skarlso** [comment]
@treemillsub how did you generate the private key?

**Comment by treemillsub** [comment]
https://www.base64encode.net

**Comment by Skarlso** [comment]
No, I mean how did you generate your key? did you generate it locally and imported it into AWS or did you generate a key from the AWS EC2 console?

**Comment by Skarlso** [comment]
Oh! I know! You are trying to import the private key. You should be importing your public key.

You can extract the public key like this:

```
ssh-keygen -y -f ec2-key.pem
```

And then encode that output to base64. Also make sure the file's mod is `chmod 0400 file.key`.

**Comment by treemillsub** [comment]
ssh-keygen

**Comment by treemillsub** [comment]
ohh yeah that was the problem. thanks. at least now I'm not getting the same error. now it's saying that the image id  doesn't exist.:

C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The image id '[ami-ea26ce85]' does not exist (Aws::EC2::Errors::InvalidAMIIDNotFound)

**Comment by Skarlso** [comment]
Yes, you have to update the config file to have some recent data. Look for
an aws ami that you would like to use in the amazon marketplace.

**Comment by treemillsub** [comment]
yeah it works now thank you @Skarlso

**Comment by Skarlso** [comment]
Excellent! Cheers mate. :) Have fun!

**Comment by treemillsub** [comment]
thanks I almost gave up on it. Im so glad you helped @Skarlso

**Comment by Skarlso** [comment]
happy that I was able to help out :)
