### ISSUE TITLE
SSH permission denied 

### ISSUE THREAD

**Issue by treemillsub** [Skarlso/aws_minecraft#5]
when I try to ssh into the ec2 instance that was created I get permission denied. I took a look at SSHHelper file and noticed that there is no public key used there "
def ssh(ip)
      exec("ssh ec2-user@#{ip}")
    end
"
maybe that's the problem.

**Comment by Skarlso** [comment]
Please note this part in the README:

* ssh this will ssh into your instance. For this to work, you'll have to load your private key into the ssh agent which belongs to the public key in your instance. To do this, run ssh-add like this: ssh-add ~/.ssh/minecraft_rsa. NOTE: This is an important part. SSH needs to be able to work for uploading your files and the world as well.
